// Vendor-style Gowin rPLL wrapper for GW1NZ-1.
// Generated by aligning the defparam set with the Sipeed
// TangNano-1K-examples/example_lcd/lcd_480_272/src/gowin_rpll/gowin_rpll.v
// reference; the open-source minimal-defparam wrapper style was unreliable
// on hardware (see ../pll-findings.md). Picking the full vendor defparam
// set materially improved hardware behavior.
//
// PLL_FREQ selects the output frequency. Each variant keeps:
//   FCLKIN = 27 MHz, IDIV_SEL=0 (PFD=27 MHz), CLKFB internal,
//   VCO = CLKOUT * (ODIV_SEL+1?) — see Gowin UG286: VCO = CLKOUT * ODIV_SEL,
//   constrained to 400..800 MHz.
//
//   54  MHz : FBDIV_SEL=1  ODIV_SEL=8   VCO=432 MHz
//   81  MHz : FBDIV_SEL=2  ODIV_SEL=8   VCO=648 MHz
//   108 MHz : FBDIV_SEL=3  ODIV_SEL=4   VCO=432 MHz

module gowin_rpll #(
    parameter PLL_FREQ = 54
) (
    input  wire clkin,
    output wire clkout,
    output wire lock
);

    wire clkoutp_o;
    wire clkoutd_o;
    wire clkoutd3_o;
    wire gw_gnd;

    assign gw_gnd = 1'b0;

    rPLL rpll_inst (
        .CLKOUT  (clkout),
        .LOCK    (lock),
        .CLKOUTP (clkoutp_o),
        .CLKOUTD (clkoutd_o),
        .CLKOUTD3(clkoutd3_o),
        .RESET   (gw_gnd),
        .RESET_P (gw_gnd),
        .CLKIN   (clkin),
        .CLKFB   (gw_gnd),
        .FBDSEL  (6'b0),
        .IDSEL   (6'b0),
        .ODSEL   (6'b0),
        .PSDA    (4'b0),
        .DUTYDA  (4'b0),
        .FDLY    (4'b0)
    );

    defparam rpll_inst.FCLKIN          = "27";
    defparam rpll_inst.DYN_IDIV_SEL    = "false";
    defparam rpll_inst.IDIV_SEL        = 0;
    defparam rpll_inst.DYN_FBDIV_SEL   = "false";
    defparam rpll_inst.FBDIV_SEL       = (PLL_FREQ == 108) ? 3 :
                                         (PLL_FREQ ==  81) ? 2 : 1;
    defparam rpll_inst.DYN_ODIV_SEL    = "false";
    defparam rpll_inst.ODIV_SEL        = (PLL_FREQ == 108) ? 4 : 8;
    defparam rpll_inst.PSDA_SEL        = "0000";
    defparam rpll_inst.DYN_DA_EN       = "true";
    defparam rpll_inst.DUTYDA_SEL      = "1000";
    defparam rpll_inst.CLKOUT_FT_DIR   = 1'b1;
    defparam rpll_inst.CLKOUTP_FT_DIR  = 1'b1;
    defparam rpll_inst.CLKOUT_DLY_STEP = 0;
    defparam rpll_inst.CLKOUTP_DLY_STEP= 0;
    defparam rpll_inst.CLKFB_SEL       = "internal";
    defparam rpll_inst.CLKOUT_BYPASS   = "false";
    defparam rpll_inst.CLKOUTP_BYPASS  = "false";
    defparam rpll_inst.CLKOUTD_BYPASS  = "false";
    defparam rpll_inst.DYN_SDIV_SEL    = 2;
    defparam rpll_inst.CLKOUTD_SRC     = "CLKOUT";
    defparam rpll_inst.CLKOUTD3_SRC    = "CLKOUT";
    defparam rpll_inst.DEVICE          = "GW1NZ-1";

endmodule
